/**
 * 시스템 공통 타입 정의 v4.2 (2026-06-09)
 * audit_logs · activity_feeds · notifications 공유
 * 저장 타입: VARCHAR(30) SCREAMING_SNAKE_CASE
 * v4.2: FEED_POST→POST, FEED_COMMENT→POST_COMMENT, FEED_LIKE→POST_LIKE,
 *       MESSAGE_ATTACHMENT→ATTACHMENT, ActionType.REJECT 추가
 */

const TargetType = Object.freeze({
  // 시스템 (1)
  REMINDER: 'REMINDER',

  // 계정 (10~12)
  USER: 'USER',
  USER_DEVICE: 'USER_DEVICE',
  USER_SETTING: 'USER_SETTING',

  // 서랍 (20~23)
  DRAWER: 'DRAWER',
  DRAWER_MEMBER: 'DRAWER_MEMBER',
  DRAWER_SETTING: 'DRAWER_SETTING',
  DRAWER_INVITATION: 'DRAWER_INVITATION',
  DRAWER_BOOST: 'DRAWER_BOOST',

  // 포스트 (25~27)
  POST: 'POST',
  POST_COMMENT: 'POST_COMMENT',
  POST_LIKE: 'POST_LIKE',

  // 캘린더 (30~31)
  CALENDAR: 'CALENDAR',
  CALENDAR_SUBSCRIPTION: 'CALENDAR_SUBSCRIPTION',

  // 시리즈·메시지 (40~48)
  SERIES: 'SERIES',
  SERIES_MESSAGE: 'SERIES_MESSAGE',
  ATTACHMENT: 'ATTACHMENT',
  MESSAGE_EMBED: 'MESSAGE_EMBED',
  MESSAGE_REACTION: 'MESSAGE_REACTION',
  MESSAGE_MENTION: 'MESSAGE_MENTION',
  MESSAGE_POLL: 'MESSAGE_POLL',
  MESSAGE_POLL_OPTION: 'MESSAGE_POLL_OPTION',
  MESSAGE_POLL_VOTE: 'MESSAGE_POLL_VOTE',

  // 이벤트 (50~53)
  EVENT: 'EVENT',
  EVENT_INSTANCE: 'EVENT_INSTANCE',
  EVENT_PARTICIPANT: 'EVENT_PARTICIPANT',
  EVENT_SERIES: 'EVENT_SERIES',

  // 태스크 (60~63)
  TASK: 'TASK',
  TASK_INSTANCE: 'TASK_INSTANCE',
  TASK_PARTICIPANT: 'TASK_PARTICIPANT',
  TASK_SERIES: 'TASK_SERIES',

  // 기념일·공휴일 (70~71)
  SPECIAL_DAY: 'SPECIAL_DAY',
  HOLIDAY: 'HOLIDAY',

  // 캐스트 (75~77)
  CAST: 'CAST',
  CAST_COMMENT: 'CAST_COMMENT',

  // 빌링 (80~82)
  SUBSCRIPTION: 'SUBSCRIPTION',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
  USER_ASSET: 'USER_ASSET',
});

const ActionType = Object.freeze({
  // CRUD (1~5)
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  RESTORE: 'RESTORE',
  HARD_DELETE: 'HARD_DELETE',

  // 멤버십 (10~13)
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  KICK: 'KICK',
  ROLE_CHANGE: 'ROLE_CHANGE',

  // 캘린더·태스크 (20~28)
  RSVP_UPDATE: 'RSVP_UPDATE',
  REJECT: 'REJECT',
  ASSIGN: 'ASSIGN',
  UNASSIGN: 'UNASSIGN',
  COMPLETE: 'COMPLETE',
  UNCOMPLETE: 'UNCOMPLETE',
  FORK: 'FORK',
  SUBSCRIBE: 'SUBSCRIBE',
  UNSUBSCRIBE: 'UNSUBSCRIBE',

  // 메시지·소셜 (30~33)
  PIN: 'PIN',
  UNPIN: 'UNPIN',
  REACT: 'REACT',
  UNREACT: 'UNREACT',

  // 빌링 (40~49)
  PURCHASE: 'PURCHASE',
  RENEW: 'RENEW',
  CANCEL_SUBSCRIPTION: 'CANCEL_SUBSCRIPTION',
  EXPIRE_SUBSCRIPTION: 'EXPIRE_SUBSCRIPTION',
  REFUND: 'REFUND',
  UPGRADE_PLAN: 'UPGRADE_PLAN',
  DOWNGRADE_PLAN: 'DOWNGRADE_PLAN',
  GRACE_PERIOD_START: 'GRACE_PERIOD_START',
  REINSTATE_SUBSCRIPTION: 'REINSTATE_SUBSCRIPTION',
  PURCHASE_ASSET: 'PURCHASE_ASSET',
});

module.exports = { TargetType, ActionType };
